[package]
name = "rust-chainlink-ea"
version = "0.1.0"
authors = ["Péter Garamvölgyi <th307q@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2.5"